In [ ]:
import meraki

In [ ]:
dashboard = meraki.DashboardAPI('10a78480dc9a24f34bcf796eaa9144c197e3d8de')

In [ ]:
org_id = dashboard.organizations.getOrganizations()
print(org_id)

In [ ]:
network_ids = dashboard.organizations.getOrganizationNetworks('25998')
print(network_ids)

In [ ]:
response = dashboard.sensor.getNetworkSensorAlertsProfiles("L_570831252769210724")
print(response)

In [1]:
import polars as pl
import glob

In [2]:
filepaths = glob.glob("meraki-webhooks-to-s3*")

In [3]:
lazy_frame = pl.scan_ndjson(filepaths)
df = lazy_frame.collect()
display(df)

shape: (43, 5)
┌──────────────────────┬────────────────┬──────────────────────┬─────────────┬─────────────────────┐
│ timestamp            ┆ source         ┆ lambda_request_id    ┆ environment ┆ payload             │
│ ---                  ┆ ---            ┆ ---                  ┆ ---         ┆ ---                 │
│ str                  ┆ str            ┆ str                  ┆ str         ┆ struct[22]          │
╞══════════════════════╪════════════════╪══════════════════════╪═════════════╪═════════════════════╡
│ 2025-10-14T12:46:43. ┆ meraki-webhook ┆ efbb0475-9521-4b98-b ┆ non-prod    ┆ {"0.1","2154879p"," │
│ 710504               ┆                ┆ c52-79ed6d…          ┆             ┆ 2025-10-14T…        │
│ 2025-10-14T12:32:55. ┆ meraki-webhook ┆ 41a406e7-4478-4f70-8 ┆ non-prod    ┆ {"0.1","2154879p"," │
│ 167410               ┆                ┆ 668-16c7d0…          ┆             ┆ 2025-10-14T…        │
│ 2025-10-14T12:00:10. ┆ meraki-webhook ┆ 0a5f4a96-066f-4279-a ┆ non-prod    ┆ {"0.1","2154879p"," │
│ 052561               ┆                ┆ 115-9d8731…          ┆             ┆ 2025-10-14T…        │
│ 2025-10-14T12:00:10. ┆ meraki-webhook ┆ b5b29bb2-362d-49b1-a ┆ non-prod    ┆ {"0.1","2154879p"," │
│ 040985               ┆                ┆ b0d-aaf7b1…          ┆             ┆ 2025-10-14T…        │
│ 2025-10-14T12:00:10. ┆ meraki-webhook ┆ 477fa7c6-959a-4bc2-b ┆ non-prod    ┆ {"0.1","2154879p"," │
│ 107244               ┆                ┆ 49f-67c48f…          ┆             ┆ 2025-10-14T…        │
│ …                    ┆ …              ┆ …                    ┆ …           ┆ …                   │
│ 2025-10-14T12:22:50. ┆ meraki-webhook ┆ 4d06863f-d1e7-4a48-a ┆ non-prod    ┆ {"0.1","2154879p"," │
│ 593945               ┆                ┆ d71-9424ef…          ┆             ┆ 2025-10-14T…        │
│ 2025-10-14T12:24:18. ┆ meraki-webhook ┆ 3f13c745-1098-430b-8 ┆ non-prod    ┆ {"0.1","42897ahscdl │
│ 349412               ┆                ┆ 8c6-0fbb56…          ┆             ┆ k","2025-10…        │
│ 2025-10-14T12:52:35. ┆ meraki-webhook ┆ 516b7a59-8eaa-4013-b ┆ non-prod    ┆ {"0.1","2154879p"," │
│ 103033               ┆                ┆ 086-d3255a…          ┆             ┆ 2025-10-14T…        │
│ 2025-10-14T12:53:48. ┆ meraki-webhook ┆ 756f9579-9c17-4f9d-8 ┆ non-prod    ┆ {"0.1","2154879p"," │
│ 002976               ┆                ┆ a8f-2f475a…          ┆             ┆ 2025-10-14T…        │
│ 2025-10-14T12:54:53. ┆ meraki-webhook ┆ cf237634-82f4-4f4f-8 ┆ non-prod    ┆ {"0.1","2154879p"," │
│ 281893               ┆                ┆ 6d4-65bac6…          ┆             ┆ 2025-10-14T…        │
└──────────────────────┴────────────────┴──────────────────────┴─────────────┴─────────────────────┘

In [4]:
df = df.unnest('payload')

In [5]:
display(df)

shape: (43, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ source    ┆ lambda_re ┆ environme ┆ … ┆ alertType ┆ alertLeve ┆ occurredA ┆ alertDat │
│ ---       ┆ ---       ┆ quest_id  ┆ nt        ┆   ┆ Id        ┆ l         ┆ t         ┆ a        │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ struct[4 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-10-1 ┆ meraki-we ┆ efbb0475- ┆ non-prod  ┆ … ┆ sensor_al ┆ informati ┆ 2025-10-1 ┆ {5708312 │
│ 4T12:46:4 ┆ bhook     ┆ 9521-4b98 ┆           ┆   ┆ ert       ┆ onal      ┆ 4T12:44:3 ┆ 52769515 │
│ 3.710504  ┆           ┆ -bc52-79e ┆           ┆   ┆           ┆           ┆ 9.000000Z ┆ 098,"Tem │
│           ┆           ┆ d6d…      ┆           ┆   ┆           ┆           ┆           ┆ peratu…  │
│ 2025-10-1 ┆ meraki-we ┆ 41a406e7- ┆ non-prod  ┆ … ┆ sensor_al ┆ informati ┆ 2025-10-1 ┆ {5708312 │
│ 4T12:32:5 ┆ bhook     ┆ 4478-4f70 ┆           ┆   ┆ ert       ┆ onal      ┆ 4T12:32:3 ┆ 52769515 │
│ 5.167410  ┆           ┆ -8668-16c ┆           ┆   ┆           ┆           ┆ 9.000000Z ┆ 098,"Tem │
│           ┆           ┆ 7d0…      ┆           ┆   ┆           ┆           ┆           ┆ peratu…  │
│ 2025-10-1 ┆ meraki-we ┆ 0a5f4a96- ┆ non-prod  ┆ … ┆ sensor_al ┆ informati ┆ 2025-10-1 ┆ {5708312 │
│ 4T12:00:1 ┆ bhook     ┆ 066f-4279 ┆           ┆   ┆ ert       ┆ onal      ┆ 4T11:48:5 ┆ 52769515 │
│ 0.052561  ┆           ┆ -a115-9d8 ┆           ┆   ┆           ┆           ┆ 0.000000Z ┆ 098,"Tem │
│           ┆           ┆ 731…      ┆           ┆   ┆           ┆           ┆           ┆ peratu…  │
│ 2025-10-1 ┆ meraki-we ┆ b5b29bb2- ┆ non-prod  ┆ … ┆ sensor_al ┆ informati ┆ 2025-10-1 ┆ {5708312 │
│ 4T12:00:1 ┆ bhook     ┆ 362d-49b1 ┆           ┆   ┆ ert       ┆ onal      ┆ 4T11:43:5 ┆ 52769515 │
│ 0.040985  ┆           ┆ -ab0d-aaf ┆           ┆   ┆           ┆           ┆ 9.000000Z ┆ 098,"Tem │
│           ┆           ┆ 7b1…      ┆           ┆   ┆           ┆           ┆           ┆ peratu…  │
│ 2025-10-1 ┆ meraki-we ┆ 477fa7c6- ┆ non-prod  ┆ … ┆ sensor_al ┆ informati ┆ 2025-10-1 ┆ {5708312 │
│ 4T12:00:1 ┆ bhook     ┆ 959a-4bc2 ┆           ┆   ┆ ert       ┆ onal      ┆ 4T11:41:3 ┆ 52769515 │
│ 0.107244  ┆           ┆ -b49f-67c ┆           ┆   ┆           ┆           ┆ 3.000000Z ┆ 098,"Tem │
│           ┆           ┆ 48f…      ┆           ┆   ┆           ┆           ┆           ┆ peratu…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-10-1 ┆ meraki-we ┆ 4d06863f- ┆ non-prod  ┆ … ┆ sensor_al ┆ informati ┆ 2025-10-1 ┆ {5708312 │
│ 4T12:22:5 ┆ bhook     ┆ d1e7-4a48 ┆           ┆   ┆ ert       ┆ onal      ┆ 4T12:20:4 ┆ 52769515 │
│ 0.593945  ┆           ┆ -ad71-942 ┆           ┆   ┆           ┆           ┆ 9.000000Z ┆ 098,"Tem │
│           ┆           ┆ 4ef…      ┆           ┆   ┆           ┆           ┆           ┆ peratu…  │
│ 2025-10-1 ┆ meraki-we ┆ 3f13c745- ┆ non-prod  ┆ … ┆ sensor_al ┆ informati ┆ 2025-10-1 ┆ {5708312 │
│ 4T12:24:1 ┆ bhook     ┆ 1098-430b ┆           ┆   ┆ ert       ┆ onal      ┆ 4T12:24:1 ┆ 52769524 │
│ 8.349412  ┆           ┆ -88c6-0fb ┆           ┆   ┆           ┆           ┆ 2.000000Z ┆ 948,"Tem │
│           ┆           ┆ b56…      ┆           ┆   ┆           ┆           ┆           ┆ peratu…  │
│ 2025-10-1 ┆ meraki-we ┆ 516b7a59- ┆ non-prod  ┆ … ┆ sensor_al ┆ informati ┆ 2025-10-1 ┆ {5708312 │
│ 4T12:52:3 ┆ bhook     ┆ 8eaa-4013 ┆           ┆   ┆ ert       ┆ onal      ┆ 4T12:52:1 ┆ 52769515 │
│ 5.103033  ┆           ┆ -b086-d32 ┆           ┆   ┆           ┆           ┆ 8.000000Z ┆ 098,"Tem │
│           ┆           ┆ 55a…      ┆           ┆   ┆           ┆           ┆           ┆ peratu…  │
│ 2025-10-1 ┆ meraki-we ┆ 756f9579- ┆ non-prod  ┆ … ┆ sensor_al ┆ informati ┆ 2025-10-1 ┆ {5708312 │
│ 4T12:53:4 ┆ bhook     ┆ 9c17-4f9d ┆           ┆   ┆ ert       ┆ onal      ┆ 4T12:53:4 ┆ 52769515 │
│ 8.002976  ┆           ┆ -8a8f-2f4 ┆           ┆   ┆           ┆           ┆ 2.000000Z ┆ 098,"Tem │
│           ┆           ┆ 75a…      ┆           ┆   ┆           ┆           ┆           ┆ peratu…  │
│ 2025-10-1 ┆ meraki-we ┆ cf237634- ┆ non-prod  ┆ … ┆ sensor_al ┆ informati ┆ 2025-10-1 ┆ {5708312 │
│ 4T12:54:5 ┆ bhook     ┆ 82f4-4f4f ┆           ┆   ┆ ert       ┆ onal      ┆ 4T12:54:4 ┆ 52769515 │
│ 3.281893  ┆           ┆ -86d4-65b ┆           ┆   ┆           ┆           ┆ 0.000000Z ┆ 098,"Tem │
│           ┆           ┆ ac6…      ┆           ┆   ┆           ┆           ┆           ┆ peratu…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
df = df.unnest('alertData')
display(df)

shape: (43, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ source    ┆ lambda_re ┆ environme ┆ … ┆ alertConf ┆ alertConf ┆ triggerDa ┆ startedA │
│ ---       ┆ ---       ┆ quest_id  ┆ nt        ┆   ┆ igId      ┆ igName    ┆ ta        ┆ lerting  │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ i64       ┆ str       ┆ list[stru ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ct[2]]    ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-10-1 ┆ meraki-we ┆ efbb0475- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ [{5708312 ┆ true     │
│ 4T12:46:4 ┆ bhook     ┆ 9521-4b98 ┆           ┆   ┆ 769515098 ┆ re        ┆ 527692106 ┆          │
│ 3.710504  ┆           ┆ -bc52-79e ┆           ┆   ┆           ┆ Threshold ┆ 81,{1.760 ┆          │
│           ┆           ┆ d6d…      ┆           ┆   ┆           ┆ FB        ┆ 4e9…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 41a406e7- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ [{5708312 ┆ false    │
│ 4T12:32:5 ┆ bhook     ┆ 4478-4f70 ┆           ┆   ┆ 769515098 ┆ re        ┆ 527692106 ┆          │
│ 5.167410  ┆           ┆ -8668-16c ┆           ┆   ┆           ┆ Threshold ┆ 81,{1.760 ┆          │
│           ┆           ┆ 7d0…      ┆           ┆   ┆           ┆ FB        ┆ 4e9…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 0a5f4a96- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ [{5708312 ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 066f-4279 ┆           ┆   ┆ 769515098 ┆ re        ┆ 527692106 ┆          │
│ 0.052561  ┆           ┆ -a115-9d8 ┆           ┆   ┆           ┆ Threshold ┆ 81,{1.760 ┆          │
│           ┆           ┆ 731…      ┆           ┆   ┆           ┆ FB        ┆ 4e9…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ b5b29bb2- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ [{5708312 ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 362d-49b1 ┆           ┆   ┆ 769515098 ┆ re        ┆ 527692106 ┆          │
│ 0.040985  ┆           ┆ -ab0d-aaf ┆           ┆   ┆           ┆ Threshold ┆ 81,{1.760 ┆          │
│           ┆           ┆ 7b1…      ┆           ┆   ┆           ┆ FB        ┆ 4e9…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 477fa7c6- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ [{5708312 ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 959a-4bc2 ┆           ┆   ┆ 769515098 ┆ re        ┆ 527692106 ┆          │
│ 0.107244  ┆           ┆ -b49f-67c ┆           ┆   ┆           ┆ Threshold ┆ 81,{1.760 ┆          │
│           ┆           ┆ 48f…      ┆           ┆   ┆           ┆ FB        ┆ 4e9…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-10-1 ┆ meraki-we ┆ 4d06863f- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ [{5708312 ┆ true     │
│ 4T12:22:5 ┆ bhook     ┆ d1e7-4a48 ┆           ┆   ┆ 769515098 ┆ re        ┆ 527692106 ┆          │
│ 0.593945  ┆           ┆ -ad71-942 ┆           ┆   ┆           ┆ Threshold ┆ 81,{1.760 ┆          │
│           ┆           ┆ 4ef…      ┆           ┆   ┆           ┆ FB        ┆ 4e9…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 3f13c745- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ [{5708312 ┆ false    │
│ 4T12:24:1 ┆ bhook     ┆ 1098-430b ┆           ┆   ┆ 769524948 ┆ re        ┆ 527692106 ┆          │
│ 8.349412  ┆           ┆ -88c6-0fb ┆           ┆   ┆           ┆ Threshold ┆ 84,{1.760 ┆          │
│           ┆           ┆ b56…      ┆           ┆   ┆           ┆ HSLA-MA   ┆ 4e9…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 516b7a59- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ [{5708312 ┆ false    │
│ 4T12:52:3 ┆ bhook     ┆ 8eaa-4013 ┆           ┆   ┆ 769515098 ┆ re        ┆ 527692106 ┆          │
│ 5.103033  ┆           ┆ -b086-d32 ┆           ┆   ┆           ┆ Threshold ┆ 81,{1.760 ┆          │
│           ┆           ┆ 55a…      ┆           ┆   ┆           ┆ FB        ┆ 4e9…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 756f9579- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ [{5708312 ┆ false    │
│ 4T12:53:4 ┆ bhook     ┆ 9c17-4f9d ┆           ┆   ┆ 769515098 ┆ re        ┆ 527692106 ┆          │
│ 8.002976  ┆           ┆ -8a8f-2f4 ┆           ┆   ┆           ┆ Threshold ┆ 81,{1.760 ┆          │
│           ┆           ┆ 75a…      ┆           ┆   ┆           ┆ FB        ┆ 4e9…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ cf237634- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ [{5708312 ┆ false    │
│ 4T12:54:5 ┆ bhook     ┆ 82f4-4f4f ┆           ┆   ┆ 769515098 ┆ re        ┆ 527692106 ┆          │
│ 3.281893  ┆           ┆ -86d4-65b ┆           ┆   ┆           ┆ Threshold ┆ 81,{1.760 ┆          │
│           ┆           ┆ ac6…      ┆           ┆   ┆           ┆ FB        ┆ 4e9…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
df = df.explode('triggerData')
display(df)

shape: (43, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ source    ┆ lambda_re ┆ environme ┆ … ┆ alertConf ┆ alertConf ┆ triggerDa ┆ startedA │
│ ---       ┆ ---       ┆ quest_id  ┆ nt        ┆   ┆ igId      ┆ igName    ┆ ta        ┆ lerting  │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ i64       ┆ str       ┆ struct[2] ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-10-1 ┆ meraki-we ┆ efbb0475- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ {57083125 ┆ true     │
│ 4T12:46:4 ┆ bhook     ┆ 9521-4b98 ┆           ┆   ┆ 769515098 ┆ re        ┆ 276921068 ┆          │
│ 3.710504  ┆           ┆ -bc52-79e ┆           ┆   ┆           ┆ Threshold ┆ 1,{1.7604 ┆          │
│           ┆           ┆ d6d…      ┆           ┆   ┆           ┆ FB        ┆ e9,…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 41a406e7- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ {57083125 ┆ false    │
│ 4T12:32:5 ┆ bhook     ┆ 4478-4f70 ┆           ┆   ┆ 769515098 ┆ re        ┆ 276921068 ┆          │
│ 5.167410  ┆           ┆ -8668-16c ┆           ┆   ┆           ┆ Threshold ┆ 1,{1.7604 ┆          │
│           ┆           ┆ 7d0…      ┆           ┆   ┆           ┆ FB        ┆ e9,…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 0a5f4a96- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ {57083125 ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 066f-4279 ┆           ┆   ┆ 769515098 ┆ re        ┆ 276921068 ┆          │
│ 0.052561  ┆           ┆ -a115-9d8 ┆           ┆   ┆           ┆ Threshold ┆ 1,{1.7604 ┆          │
│           ┆           ┆ 731…      ┆           ┆   ┆           ┆ FB        ┆ e9,…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ b5b29bb2- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ {57083125 ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 362d-49b1 ┆           ┆   ┆ 769515098 ┆ re        ┆ 276921068 ┆          │
│ 0.040985  ┆           ┆ -ab0d-aaf ┆           ┆   ┆           ┆ Threshold ┆ 1,{1.7604 ┆          │
│           ┆           ┆ 7b1…      ┆           ┆   ┆           ┆ FB        ┆ e9,…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 477fa7c6- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ {57083125 ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 959a-4bc2 ┆           ┆   ┆ 769515098 ┆ re        ┆ 276921068 ┆          │
│ 0.107244  ┆           ┆ -b49f-67c ┆           ┆   ┆           ┆ Threshold ┆ 1,{1.7604 ┆          │
│           ┆           ┆ 48f…      ┆           ┆   ┆           ┆ FB        ┆ e9,…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-10-1 ┆ meraki-we ┆ 4d06863f- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ {57083125 ┆ true     │
│ 4T12:22:5 ┆ bhook     ┆ d1e7-4a48 ┆           ┆   ┆ 769515098 ┆ re        ┆ 276921068 ┆          │
│ 0.593945  ┆           ┆ -ad71-942 ┆           ┆   ┆           ┆ Threshold ┆ 1,{1.7604 ┆          │
│           ┆           ┆ 4ef…      ┆           ┆   ┆           ┆ FB        ┆ e9,…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 3f13c745- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ {57083125 ┆ false    │
│ 4T12:24:1 ┆ bhook     ┆ 1098-430b ┆           ┆   ┆ 769524948 ┆ re        ┆ 276921068 ┆          │
│ 8.349412  ┆           ┆ -88c6-0fb ┆           ┆   ┆           ┆ Threshold ┆ 4,{1.7604 ┆          │
│           ┆           ┆ b56…      ┆           ┆   ┆           ┆ HSLA-MA   ┆ e9,…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 516b7a59- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ {57083125 ┆ false    │
│ 4T12:52:3 ┆ bhook     ┆ 8eaa-4013 ┆           ┆   ┆ 769515098 ┆ re        ┆ 276921068 ┆          │
│ 5.103033  ┆           ┆ -b086-d32 ┆           ┆   ┆           ┆ Threshold ┆ 1,{1.7604 ┆          │
│           ┆           ┆ 55a…      ┆           ┆   ┆           ┆ FB        ┆ e9,…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 756f9579- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ {57083125 ┆ false    │
│ 4T12:53:4 ┆ bhook     ┆ 9c17-4f9d ┆           ┆   ┆ 769515098 ┆ re        ┆ 276921068 ┆          │
│ 8.002976  ┆           ┆ -8a8f-2f4 ┆           ┆   ┆           ┆ Threshold ┆ 1,{1.7604 ┆          │
│           ┆           ┆ 75a…      ┆           ┆   ┆           ┆ FB        ┆ e9,…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ cf237634- ┆ non-prod  ┆ … ┆ 570831252 ┆ Temperatu ┆ {57083125 ┆ false    │
│ 4T12:54:5 ┆ bhook     ┆ 82f4-4f4f ┆           ┆   ┆ 769515098 ┆ re        ┆ 276921068 ┆          │
│ 3.281893  ┆           ┆ -86d4-65b ┆           ┆   ┆           ┆ Threshold ┆ 1,{1.7604 ┆          │
│           ┆           ┆ ac6…      ┆           ┆   ┆           ┆ FB        ┆ e9,…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
df = df.unnest('triggerData')
display(df)

shape: (43, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ source    ┆ lambda_re ┆ environme ┆ … ┆ alertConf ┆ condition ┆ trigger   ┆ startedA │
│ ---       ┆ ---       ┆ quest_id  ┆ nt        ┆   ┆ igName    ┆ Id        ┆ ---       ┆ lerting  │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ struct[4] ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ i64       ┆           ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-10-1 ┆ meraki-we ┆ efbb0475- ┆ non-prod  ┆ … ┆ Temperatu ┆ 570831252 ┆ {1.7604e9 ┆ true     │
│ 4T12:46:4 ┆ bhook     ┆ 9521-4b98 ┆           ┆   ┆ re        ┆ 769210681 ┆ ,"tempera ┆          │
│ 3.710504  ┆           ┆ -bc52-79e ┆           ┆   ┆ Threshold ┆           ┆ ture",206 ┆          │
│           ┆           ┆ d6d…      ┆           ┆   ┆ FB        ┆           ┆ 928…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 41a406e7- ┆ non-prod  ┆ … ┆ Temperatu ┆ 570831252 ┆ {1.7604e9 ┆ false    │
│ 4T12:32:5 ┆ bhook     ┆ 4478-4f70 ┆           ┆   ┆ re        ┆ 769210681 ┆ ,"tempera ┆          │
│ 5.167410  ┆           ┆ -8668-16c ┆           ┆   ┆ Threshold ┆           ┆ ture",206 ┆          │
│           ┆           ┆ 7d0…      ┆           ┆   ┆ FB        ┆           ┆ 928…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 0a5f4a96- ┆ non-prod  ┆ … ┆ Temperatu ┆ 570831252 ┆ {1.7604e9 ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 066f-4279 ┆           ┆   ┆ re        ┆ 769210681 ┆ ,"tempera ┆          │
│ 0.052561  ┆           ┆ -a115-9d8 ┆           ┆   ┆ Threshold ┆           ┆ ture",206 ┆          │
│           ┆           ┆ 731…      ┆           ┆   ┆ FB        ┆           ┆ 928…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ b5b29bb2- ┆ non-prod  ┆ … ┆ Temperatu ┆ 570831252 ┆ {1.7604e9 ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 362d-49b1 ┆           ┆   ┆ re        ┆ 769210681 ┆ ,"tempera ┆          │
│ 0.040985  ┆           ┆ -ab0d-aaf ┆           ┆   ┆ Threshold ┆           ┆ ture",206 ┆          │
│           ┆           ┆ 7b1…      ┆           ┆   ┆ FB        ┆           ┆ 928…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 477fa7c6- ┆ non-prod  ┆ … ┆ Temperatu ┆ 570831252 ┆ {1.7604e9 ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 959a-4bc2 ┆           ┆   ┆ re        ┆ 769210681 ┆ ,"tempera ┆          │
│ 0.107244  ┆           ┆ -b49f-67c ┆           ┆   ┆ Threshold ┆           ┆ ture",206 ┆          │
│           ┆           ┆ 48f…      ┆           ┆   ┆ FB        ┆           ┆ 928…      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-10-1 ┆ meraki-we ┆ 4d06863f- ┆ non-prod  ┆ … ┆ Temperatu ┆ 570831252 ┆ {1.7604e9 ┆ true     │
│ 4T12:22:5 ┆ bhook     ┆ d1e7-4a48 ┆           ┆   ┆ re        ┆ 769210681 ┆ ,"tempera ┆          │
│ 0.593945  ┆           ┆ -ad71-942 ┆           ┆   ┆ Threshold ┆           ┆ ture",206 ┆          │
│           ┆           ┆ 4ef…      ┆           ┆   ┆ FB        ┆           ┆ 928…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 3f13c745- ┆ non-prod  ┆ … ┆ Temperatu ┆ 570831252 ┆ {1.7604e9 ┆ false    │
│ 4T12:24:1 ┆ bhook     ┆ 1098-430b ┆           ┆   ┆ re        ┆ 769210684 ┆ ,"tempera ┆          │
│ 8.349412  ┆           ┆ -88c6-0fb ┆           ┆   ┆ Threshold ┆           ┆ ture",206 ┆          │
│           ┆           ┆ b56…      ┆           ┆   ┆ HSLA-MA   ┆           ┆ 928…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 516b7a59- ┆ non-prod  ┆ … ┆ Temperatu ┆ 570831252 ┆ {1.7604e9 ┆ false    │
│ 4T12:52:3 ┆ bhook     ┆ 8eaa-4013 ┆           ┆   ┆ re        ┆ 769210681 ┆ ,"tempera ┆          │
│ 5.103033  ┆           ┆ -b086-d32 ┆           ┆   ┆ Threshold ┆           ┆ ture",206 ┆          │
│           ┆           ┆ 55a…      ┆           ┆   ┆ FB        ┆           ┆ 928…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 756f9579- ┆ non-prod  ┆ … ┆ Temperatu ┆ 570831252 ┆ {1.7604e9 ┆ false    │
│ 4T12:53:4 ┆ bhook     ┆ 9c17-4f9d ┆           ┆   ┆ re        ┆ 769210681 ┆ ,"tempera ┆          │
│ 8.002976  ┆           ┆ -8a8f-2f4 ┆           ┆   ┆ Threshold ┆           ┆ ture",206 ┆          │
│           ┆           ┆ 75a…      ┆           ┆   ┆ FB        ┆           ┆ 928…      ┆          │
│ 2025-10-1 ┆ meraki-we ┆ cf237634- ┆ non-prod  ┆ … ┆ Temperatu ┆ 570831252 ┆ {1.7604e9 ┆ false    │
│ 4T12:54:5 ┆ bhook     ┆ 82f4-4f4f ┆           ┆   ┆ re        ┆ 769210681 ┆ ,"tempera ┆          │
│ 3.281893  ┆           ┆ -86d4-65b ┆           ┆   ┆ Threshold ┆           ┆ ture",206 ┆          │
│           ┆           ┆ ac6…      ┆           ┆   ┆ FB        ┆           ┆ 928…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df = df.unnest('trigger')
display(df)

shape: (43, 33)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ source    ┆ lambda_re ┆ environme ┆ … ┆ type      ┆ nodeId    ┆ sensorVal ┆ startedA │
│ ---       ┆ ---       ┆ quest_id  ┆ nt        ┆   ┆ ---       ┆ ---       ┆ ue        ┆ lerting  │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ i64       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆           ┆ f64       ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-10-1 ┆ meraki-we ┆ efbb0475- ┆ non-prod  ┆ … ┆ temperatu ┆ 206928319 ┆ 18.277779 ┆ true     │
│ 4T12:46:4 ┆ bhook     ┆ 9521-4b98 ┆           ┆   ┆ re        ┆ 859394    ┆           ┆          │
│ 3.710504  ┆           ┆ -bc52-79e ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ d6d…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 41a406e7- ┆ non-prod  ┆ … ┆ temperatu ┆ 206928319 ┆ 18.388889 ┆ false    │
│ 4T12:32:5 ┆ bhook     ┆ 4478-4f70 ┆           ┆   ┆ re        ┆ 859394    ┆           ┆          │
│ 5.167410  ┆           ┆ -8668-16c ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 7d0…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 0a5f4a96- ┆ non-prod  ┆ … ┆ temperatu ┆ 206928319 ┆ 17.0      ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 066f-4279 ┆           ┆   ┆ re        ┆ 859175    ┆           ┆          │
│ 0.052561  ┆           ┆ -a115-9d8 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 731…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-10-1 ┆ meraki-we ┆ b5b29bb2- ┆ non-prod  ┆ … ┆ temperatu ┆ 206928319 ┆ 16.055555 ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 362d-49b1 ┆           ┆   ┆ re        ┆ 859683    ┆           ┆          │
│ 0.040985  ┆           ┆ -ab0d-aaf ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 7b1…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 477fa7c6- ┆ non-prod  ┆ … ┆ temperatu ┆ 206928319 ┆ 18.0      ┆ true     │
│ 4T12:00:1 ┆ bhook     ┆ 959a-4bc2 ┆           ┆   ┆ re        ┆ 859298    ┆           ┆          │
│ 0.107244  ┆           ┆ -b49f-67c ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 48f…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-10-1 ┆ meraki-we ┆ 4d06863f- ┆ non-prod  ┆ … ┆ temperatu ┆ 206928319 ┆ 18.277779 ┆ true     │
│ 4T12:22:5 ┆ bhook     ┆ d1e7-4a48 ┆           ┆   ┆ re        ┆ 859394    ┆           ┆          │
│ 0.593945  ┆           ┆ -ad71-942 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 4ef…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 3f13c745- ┆ non-prod  ┆ … ┆ temperatu ┆ 206928319 ┆ 18.333334 ┆ false    │
│ 4T12:24:1 ┆ bhook     ┆ 1098-430b ┆           ┆   ┆ re        ┆ 856530    ┆           ┆          │
│ 8.349412  ┆           ┆ -88c6-0fb ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ b56…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 516b7a59- ┆ non-prod  ┆ … ┆ temperatu ┆ 206928319 ┆ 18.333334 ┆ false    │
│ 4T12:52:3 ┆ bhook     ┆ 8eaa-4013 ┆           ┆   ┆ re        ┆ 858509    ┆           ┆          │
│ 5.103033  ┆           ┆ -b086-d32 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 55a…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-10-1 ┆ meraki-we ┆ 756f9579- ┆ non-prod  ┆ … ┆ temperatu ┆ 206928319 ┆ 18.333334 ┆ false    │
│ 4T12:53:4 ┆ bhook     ┆ 9c17-4f9d ┆           ┆   ┆ re        ┆ 859253    ┆           ┆          │
│ 8.002976  ┆           ┆ -8a8f-2f4 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 75a…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-10-1 ┆ meraki-we ┆ cf237634- ┆ non-prod  ┆ … ┆ temperatu ┆ 206928319 ┆ 18.333334 ┆ false    │
│ 4T12:54:5 ┆ bhook     ┆ 82f4-4f4f ┆           ┆   ┆ re        ┆ 859394    ┆           ┆          │
│ 3.281893  ┆           ┆ -86d4-65b ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ac6…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘